# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ruben Maharjan
#title: Graduate Teaching Assistant
email: rubenmaharjan578@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  rubenmaharjan
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: rubenmaharjan
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile1.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a highly adaptable and quick-learning professional with a remarkable aptitude for mastering new technology stacks expeditiously. I have a proven track record of developing top-tier applications and products that meet production standards. I exhibit a strong sense of accountability for my work, consistently delivering exceptional quality that exceeds expectations. As a master's graduate with 4 years of experience in Web/Desktop Application Development and Data Warehousing, I am proficient in Python, Java, JavaScript, MySQL, Snowflake, Angular, Hibernate, and Pandas.
content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: East Tennessee State University
        caption: 2021 - 2023
        sub_title: MS Computer Science
      - layout: top
        title: Kathmandu University
        caption: 2013 - 2017
        sub_title: MS Computer Science

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: East Tennessee State University
        link: https://www.etsu.edu/ehome/
        # link_text: boringcompany.com
        sub_title: Graduate Assistant
        caption: August 2021 - May 2023
        description: | # this will include new lines to allow paragraphs
          -	Instructor of CSCI 1100 (Using Information Tech) for two undergraduate classes
          -	Taught Microsoft Word, Microsoft Excel and Microsoft PowerPoint
      - layout: left
        title: Logic Information Systems
        link: https://logicinfo.com/
        # link_text: boringcompany.com
        sub_title: Intern
        caption: June 2022 - August 2022
        description: | # this will include new lines to allow paragraphs
          -	Collaborated closely with the Data Science team, contributing to assortment optimization initiatives for retail businesses, leveraging data-driven insights to enhance product offerings and maximize profitability. 
          -	Developed interactive dashboards in Power BI, enabling efficient analysis of large-scale retail datasets, leading to a remarkable 30% reduction in time spent on data analysis and improved decision-making processes.
          -	Utilized Python in Amazon Sagemaker to develop and deploy machine learning models, driving actionable insights and predictive capabilities for business processes, resulting in enhanced efficiency and optimized outcomes.
      - layout: left
        title: Logic Information Systems
        link: https://logicinfo.com/
        # link_text: boringcompany.com
        sub_title: Software Engineer II, R&D Lane
        caption: Augues 2020 - August 2021
        description: | # this will include new lines to allow paragraphs
          -	Led a team of three software developers, successfully managing and delivering a large-scale data warehouse implementation for retail organizations. 
          -	Designed, implemented, and deployed a robust data extraction architecture, utilizing various design patterns in Python to ensure efficient and reliable data processing. 
          -	Leveraged Facebook's Prophet, a powerful time series model, to forecast sales for a major US retail organization, enabling data-driven decision-making and improved inventory management. 
          -	Developed a high-performance replenishment optimization and inventory projection module, employing multiprocessing techniques in Python to enhance efficiency and accuracy. 
          -	Created a feature-rich content management system using Wagtail, Django, Azure, and PostgreSQL, empowering clients to manage and publish content seamlessly. 
          -	Implemented Python scripts for ETL/ELT processing, automating data transformations and ensuring data integrity and consistency. 
          -	Proficient in consuming and integrating data from external systems like NetSuite with SOAP (Simple Object Access Protocol) API, enabling seamless data exchange and interoperability. 
          -	Implemented Azure Data Factory (ADF) data pipelines, optimizing data loading processes into Snowflake DB, resulting in an impressive 80% reduction in data loading time.
          -	Adhered to agile development methodologies with active involvement in standup, sprint planning and retrospective meetings, and effectively using project-tracking tools like JIRA and Confluence.
      - layout: left
        title: LIS Nepal 
        link: https://lisnepal.com.np/
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: April 2018 - July 2020
        description: | # this will include new lines to allow paragraphs
          -	Designed and developed multi-tier software applications, employing industry-standard architectural patterns for scalability and maintainability. 
          -	Created robust RESTful API services, utilizing a Service Oriented Architecture (SOA) to facilitate seamless communication between components. 
          -	Configured and managed Linux server environments to ensure optimal hosting and performance of multi-tier applications. 
          -	Implemented Jenkins for efficient Continuous Integration and Continuous Deployment (CI/CD) pipelines, resulting in an impressive 80% improvement in the deployment process. 
          -	Improved application performance and user experience by implementing caching strategies, reducing page load times by an average of 30%.
          -	Played a key role in bug fixing and troubleshooting during the initial product release, ensuring a smooth and error-free user experience. 
          -	Collaborated closely with three major banks, successfully integrating banking transactions into the client's platform, enhancing functionality and user satisfaction.
      - layout: left
        title: YCO Nepal 
        link: https://lisnepal.com.np/
        # link_text: boringcompany.com
        sub_title: Associate Software Engineer
        caption: July 2017 - March 2018
        description: | # this will include new lines to allow paragraphs
          -	Developed the end-to-end development of Nepal's pioneering online stock trading platform, leveraging Angular 4 and Java 8 to deliver a seamless user experience for 49 brokers and over 100,000 online users.
          -	Employed Java Persistence API (JPA) and its implementation in J2EE to streamline performance and enhance the functionality of the platform.
          -	Implemented OAuth 2 for robust token-based authentication and authorization, ensuring secure access control for users.

      - layout: left
        title: My Hair Counts (Part-time)
        link: https://www.myhaircounts.com/
        # link_text: boringcompany.com
        sub_title: Full Stack Developer
        caption: January 2020 - June 2020
        description: | # this will include new lines to allow paragraphs
          -	Developed a mobile app using React Native and Mobx, with a Django backend, and successfully published it on the Google Play and Apple App stores.
          -	Utilized Python to enhance image security by implementing Amazon S3 for storing and accessing user-uploaded images in the mobile app.
          -	Utilized Firebase to optimize backend services, specifically for authentication and real-time database, enabling the seamless development of high-quality applications.



  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: International Storytelling Center Project
        link: https://www.storytellingcenter.net/
        link_text: International Storytelling Center
        additional_links:
          #- title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I am currently engaged in an ongoing Natural Language Processing (NLP) project in collaboration with the International Storytelling Center. The project aims to digitize and transcribe a vast historical archive of over 50 years of performance recordings, making them more easily accessible and searchable for researchers, scholars, and other interested parties. Additionally, this project allows for the development of new research and analysis methods and aims to preserve the rich history of the performances for future generations.
      - layout: top-middle
        title: Disease Diagnosis
        #link: https://www.storytellingcenter.net/
        #link_text: International Storytelling Center
        additional_links:
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          A Natural Language Processing and classification project to diagnose disease based on symptoms described by the patients using Python (Pandas, NumPy, Scikit-learn, Keras, TensorFlow) 
      - layout: top-middle
        title: Sports analytics - fantasy premier league
        #link: https://www.storytellingcenter.net/
        #link_text: International Storytelling Center
        additional_links:
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          A machine learning project with sentiment analysis to predict player performance using Python (Twitter API v2.0, VADER, Scikit-learn, Keras, TensorFlow, NLTK).

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in data and software engineering some of my other interests and hobbies are:
      - Soccer (Football as the rest of the world knows it)
      - Bagpacking
      - Reading
      - Being near water bodies

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
